JuliePro/JuliePro/Controllers/CustomerController.cs
using JuliePro.Utility;
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models.Models;
using JuliePro_Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
namespace JuliePro.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<CustomerController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public CustomerController(IUnitOfWork unitOfWork, ILogger<CustomerController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Customer()
        {
            IEnumerable<Trainer> Trainers = await _unitOfWork.Trainer.GetAllAsync();

            TrainerVM trainerVM = new TrainerVM()

            {
                Trainer = new Trainer(),
                TrainerList = Trainers.Select(t => new SelectListItem
                {
                    Text = t.FirstName,
                    Value = t.Id.ToString()
                })
            };
            return View(trainerVM);
        }
        public async Task<IActionResult> ShowO()
        {
            CustomerVM CustomerVM = new CustomerVM()
            {
                Customers = await _unitOfWork.Customer.GetAllAsync(),
                ObjectiveList = await _unitOfWork.Objective.GetAllAsync(),
                ScheduledSessionList = await _unitOfWork.ScheduledSession.GetAllAsync(),
                Trainings = await _unitOfWork.Training.GetAllAsync()
            };
            return View(CustomerVM);
        }
        public async Task<IActionResult> CustomerTracking()
        {
            IEnumerable<Customer> CustomerList = await _unitOfWork.Customer.GetAllAsync(includeProperties: "Trainer");

            return View(CustomerList);
        }

        public async Task<IActionResult> CustomerCard(int id)
        {
            CustomerVM CustomerVM = new CustomerVM()
            {
                Customer = await _unitOfWork.Customer.FirstOrDefaultAsync(c => c.Id == id),
                ObjectiveList = await _unitOfWork.Objective.GetAllAsync(o => o.Customer_Id == id),
                ScheduledSessionList = await _unitOfWork.ScheduledSession.GetAllAsync(s => s.Customer_Id == id, includeProperties: "Training")
            };
            return View(CustomerVM);
        }
    }

}

JuliePro/JuliePro/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro_DataAccess.Data;
using JuliePro_Models;
using JuliePro_Models.Models;

namespace JuliePro.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly JulieProDbContext _context;

        public EquipmentController(JulieProDbContext context)
        {
            _context = context;
        }

        // GET: Equipment
        public async Task<IActionResult> Index()
        {
            return View(await _context.Equipment.ToListAsync());
        }

        // GET: Equipment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // GET: Equipment/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Equipment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment.FindAsync(id);
            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        // POST: Equipment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Equipment equipment)
        {
            if (id != equipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipmentExists(equipment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: Equipment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipment = await _context.Equipment.FindAsync(id);
            _context.Equipment.Remove(equipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EquipmentExists(int id)
        {
            return _context.Equipment.Any(e => e.Id == id);
        }
    }
}

JuliePro/JuliePro/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro_DataAccess.Data;
using JuliePro_Models;
using JuliePro_Models.Models;

namespace JuliePro.Controllers
{
    public class SpecialityController : Controller
    {
        private readonly JulieProDbContext _context;

        public SpecialityController(JulieProDbContext context)
        {
            _context = context;
        }

        // GET: Speciality
        public async Task<IActionResult> Index()
        {
            return View(await _context.Speciality.ToListAsync());
        }

        // GET: Speciality/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speciality = await _context.Speciality
                .FirstOrDefaultAsync(m => m.Id == id);
            if (speciality == null)
            {
                return NotFound();
            }

            return View(speciality);
        }

        // GET: Speciality/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Speciality/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Speciality speciality)
        {
            if (ModelState.IsValid)
            {
                _context.Add(speciality);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(speciality);
        }

        // GET: Speciality/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speciality = await _context.Speciality.FindAsync(id);
            if (speciality == null)
            {
                return NotFound();
            }
            return View(speciality);
        }

        // POST: Speciality/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Speciality speciality)
        {
            if (id != speciality.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(speciality);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialityExists(speciality.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(speciality);
        }

        // GET: Speciality/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speciality = await _context.Speciality
                .FirstOrDefaultAsync(m => m.Id == id);
            if (speciality == null)
            {
                return NotFound();
            }

            return View(speciality);
        }

        // POST: Speciality/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var speciality = await _context.Speciality.FindAsync(id);
            _context.Speciality.Remove(speciality);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecialityExists(int id)
        {
            return _context.Speciality.Any(e => e.Id == id);
        }
    }
}

JuliePro/JuliePro/Views/Shared/_CreateBack.cshtml
@inject IViewLocalizer Localizer
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model"><i class="fas fa-plus"></i> @Locals["Create"] </button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-arrow-left"></i> @Locals["BackToList"] </a>
    </div>
</div>

JuliePro/JuliePro/Views/Shared/_DeleteBack.cshtml
@inject IViewLocalizer Localizer
<div class="row">
    <div class="col">
        <button asp-action="DeletePost" class="btn btn-danger form-control" asp-route-id="@Model"><i class="fas fa-trash-alt"></i>@Locals["Delete"]</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-arrow-left"></i>@Locals["BackToList"]</a>
    </div>
</div>

JuliePro/JuliePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JuliePro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href="~/fontawesome/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/imagesLayout/tile.png" style="width:80%" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Locals["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Locals["Privacy"]</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @Locals["Trainer"]
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="CustomerTracking"> @Locals["CreateObjTrack"]</a></li>
                                @*<li><a class="dropdown-item">Tracking Training sessions</a></li>*@
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Trainer" asp-action="Index">@Locals["Profile"]</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @Locals["Customer"]
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @*<li><a class="dropdown-item">Training sessions</a></li>
                                <li><a class="dropdown-item">Objective</a></li>*@
                                <li><a class="dropdown-item" asp-area="" asp-controller="Trainer" asp-action="Filtrer"> @Locals["OurTrainers"]</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @Locals["Admin"] 
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Training" asp-action="Index"> @Locals["Training"]</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Equipment" asp-action="Index"> @Locals["Equipment"]</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Speciality" asp-action="Index"> @Locals["Speciality"]</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Trainer" asp-action="Index"> @Locals["ManageTrainer"]</a></li>
                            </ul>
                        </li>

                    </ul>
                    <div class="col-md-2 text-right">
                        @await Html.PartialAsync("_SelectLanguage")
                    </div>
                </div>
            </div>
        </nav>
    </header><div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2021 - JuliePro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JuliePro/JuliePro/Views/Shared/_Notifications.cshtml
@using JuliePro.Utility

@if (TempData[AppContants.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
      toastr.success('@TempData[AppContants.Success]');
    </script>
}

@if (TempData[AppContants.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
  toastr.error('@TempData[AppContants.Error]');
    </script>

}

JuliePro/JuliePro/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}
<div style="display: inline-block; vertical-align: middle;">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        <div class="form-group" style="margin-bottom:0">
            <select onchange="this.form.submit()" name="culture" class="form-control btn btn-dark"
                    asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
            </select>
        </div>
    </form>
</div>

JuliePro/JuliePro/Views/Shared/_TrainerCard.cshtml
@model JuliePro_Models.Models.Trainer
@using JuliePro.Utility;


<div class="col-lg-4 col-md-6 pb-4 filter @Model.Speciality.Name.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <!--<div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-9"><label class="float-left">@Model.FirstName</label></div>-->
            @*<div class="col-3"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", Model.Price)</span></label> </div>*@
        <!--</div>-->
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@AppContants.ImagePathView@Model.Photo" alt="Image de la couverture">
        <div class="card-body p-1 px-3 row">
            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Speciality.Name</span>
            </div>

            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.FirstName</span>
            </div>
            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.LastName</span>
            </div>

            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Email</span>
            </div>
            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Biography</span>
            </div>

            <div class="col">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Photo</span>
            </div>

            
        </div>

    </div>
</div>

JuliePro/JuliePro/Views/Shared/_UpdateBack.cshtml
@inject IViewLocalizer Localizer
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model"><i class="fas fa-edit"></i>@Locals["Edit"]</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-arrow-left"></i>@Locals["BackToList"]</a>
    </div>
</div>