JuliePro/JuliePro/Controllers/CustomerController.cs
using JuliePro.Utility;
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models.Models;
using JuliePro_Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
namespace JuliePro.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<CustomerController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public CustomerController(IUnitOfWork unitOfWork, ILogger<CustomerController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Customer()
        {
            IEnumerable<Trainer> Trainers = await _unitOfWork.Trainer.GetAllAsync();

            TrainerVM trainerVM = new TrainerVM()

            {
                Trainer = new Trainer(),
                TrainerList = Trainers.Select(t => new SelectListItem
                {
                    Text = t.FirstName,
                    Value = t.Id.ToString()
                })
            };
            return View(trainerVM);
        }
        public async Task<IActionResult> ShowO()
        {
            CustomerVM CustomerVM = new CustomerVM()
            {
                Customers = await _unitOfWork.Customer.GetAllAsync(),
                ObjectiveList = await _unitOfWork.Objective.GetAllAsync(),
                ScheduledSessionList = await _unitOfWork.ScheduledSession.GetAllAsync(),
                Trainings = await _unitOfWork.Training.GetAllAsync()
            };
            return View(CustomerVM);
        }
        public async Task<IActionResult> CustomerTracking()
        {
            IEnumerable<Customer> CustomerList = await _unitOfWork.Customer.GetAllAsync(includeProperties: "Trainer");

            return View(CustomerList);
        }

        public async Task<IActionResult> CustomerCard(int id)
        {
            CustomerVM CustomerVM = new CustomerVM()
            {
                Customer = await _unitOfWork.Customer.FirstOrDefaultAsync(c => c.Id == id),
                ObjectiveList = await _unitOfWork.Objective.GetAllAsync(o => o.Customer_Id == id),
                ScheduledSessionList = await _unitOfWork.ScheduledSession.GetAllAsync(s => s.Customer_Id == id, includeProperties: "Training")
            };
            return View(CustomerVM);
        }
    }

}

JuliePro/JuliePro/Controllers/ObjectiveController.cs
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models.Models;
using JuliePro_Models.ViewModels;
using JuliePro_Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JuliePro.Controllers
{
    public class ObjectiveController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<ObjectiveController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ObjectiveService _service;

        public ObjectiveController(IUnitOfWork unitOfWork, ILogger<ObjectiveController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
            _service = new ObjectiveService(this.ModelState, _unitOfWork);
        }

        public IActionResult Index(int Id)
        {
            return View("CustomerTracking", "Customer");
        }

        public async Task<IActionResult> ShowO()
        {
            IEnumerable <Customer> Customers= await _unitOfWork.Customer.GetAllAsync();
            return View(Customers);
        }

        public async Task<IActionResult> Create(int Id)
        {
            Objective objective = new Objective();
            Customer customer = await _unitOfWork.Customer.FirstOrDefaultAsync(c => c.Id == Id);

            ObjectiveVM objectiveVM = new ObjectiveVM()
            {
                Objective = objective,
                CustomerName = customer.FirstName + " " + customer.LastName,
                CustomerId = Id

            };
            return View(objectiveVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ObjectiveVM objectiveVM)
        {

            Objective objective = objectiveVM.Objective;

            if (!_service.CreateObjective(objective))
            {
                // Ajouter à la BD
                ModelState.AddModelError("", "Complete the objectives first");
                return View(objectiveVM);
            }
            return RedirectToAction("CustomerCard", "Customer", new { Id = objectiveVM.Objective.Customer_Id });


        }
    }
}

JuliePro/JuliePro/Controllers/ScheduledSessionController.cs
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models.Models;
using JuliePro_Models.ViewModels;
using JuliePro_Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JuliePro.Controllers
{
    public class ScheduledSessionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<ScheduledSessionController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ScheduledSessionService _service;

        public ScheduledSessionController(IUnitOfWork unitOfWork, ILogger<ScheduledSessionController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
            _service = new ScheduledSessionService( _unitOfWork);
        }

        public IActionResult Index(int Id)
        {
            return View("CustomerTracking", "Customer");
        }

        public async Task<IActionResult> ShowS()
        {
            IEnumerable<ScheduledSession> ScheduledSessions = await _unitOfWork.ScheduledSession.GetAllAsync();
            return View(ScheduledSessions);
        }

        public async Task<IActionResult> Create(int Id)
        {
            ScheduledSession scheduledSession = new ScheduledSession();
            Customer customer = await _unitOfWork.Customer.FirstOrDefaultAsync(c => c.Id == Id);
            IEnumerable<Training> trainings = _unitOfWork.Training.GetAll();

            ScheduledSessionVM scheduledSessionVM = new ScheduledSessionVM()
            {
                ScheduledSession = scheduledSession,
                CustomerName = customer.FirstName + " " + customer.LastName,
                CustomerId = Id,
                TrainingList = trainings.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })


            };
            return View(scheduledSessionVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ScheduledSessionVM scheduledSessionVM)
        {

            ScheduledSession scheduledSession = scheduledSessionVM.ScheduledSession;

            if (!_service.CreateScheduledSession(scheduledSession))
            {
                // Ajouter à la BD
                ModelState.AddModelError("", " those ScheduledSessions are enough ");
                IEnumerable<Training> trainings = _unitOfWork.Training.GetAll();
                scheduledSessionVM.TrainingList = trainings.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

                return View(scheduledSessionVM);
            }
            return RedirectToAction("CustomerCard", "Customer", new { Id = scheduledSessionVM.ScheduledSession.Customer_Id });


        }
    }
}

JuliePro/JuliePro/Views/Customer/CustomerCard.cshtml
@model JuliePro_Models.ViewModels.CustomerVM

    <div class="card pb-3">
        <div class="card-header pb-3 bg-dark text-light ml-0 row container">
            <div class="col-6">
                <i class="fas fa-book"></i> &nbsp;
                Customer
            </div>
            <div class="col-4 text-right">
                <a asp-controller="Objective" asp-action="Create" asp-route-id="@Model.Customer.Id" class="btn btn-outline-info">Add an objective</a>
            </div>

        </div>
        <div class="card-body">
            <div class="container rounded p-2">
                <div class="row">
                    <div class="col-12 col-lg-6 pb-4">
                        <div class="row">

                            <h4 class="d-flex justify-content-between align-items-center">
                                <span class="text-info">Customer, Objectives and ScheduledSession</span>
                            </h4>
                        </div>
                        <div class="row my-1">
                            <div class="col-3">
                                <label>Customer LastName</label>
                            </div>
                            <div class="col-9">
                                <input asp-for="Customer.LastName" type="text" class="form-control" />
                                <span asp-validation-for="Customer.LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row my-1">
                            <div class="col-3">
                                <label>Customer Firstname</label>
                            </div>
                            <div class="col-9">
                                <input asp-for="Customer.FirstName" type="text" class="form-control" />
                                <span asp-validation-for="Customer.FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row my-1">
                            <div class="col-3">
                                <label>BirthDate</label>
                            </div>
                            <div class="col-9">
                                <input asp-for="Customer.BirthDate" type="text" class="form-control" />
                                <span asp-validation-for="Customer.BirthDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row my-1">
                            <div class="col-3">
                                <label>Email</label>
                            </div>
                            <div class="col-9">
                                <input asp-for="Customer.Email" type="text" class="form-control" />
                                <span asp-validation-for="Customer.Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row my-1">
                            <div class="col-3">
                                <label>StartWeight</label>
                            </div>
                            <div class="col-9">
                                <input asp-for="Customer.StartWeight" type="text" class="form-control" />
                                <span asp-validation-for="Customer.StartWeight" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-5 offset-lg-1">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-info">Customer Objectives:</span>
                        </h4>
                        <ul class="list-group mb-3">
                            @foreach (var details in Model.ObjectiveList.OrderByDescending(o => o.Name))
                            {
                            <li class="list-group-item d-flex justify-content-between">
                                <label>Name</label>
                                <div>
                                    <p class="my-0">@details.Name</p>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between">
                                <label>LostWeight</label>
                                <div>
                                    <p class="my-0">@details.LostWeight</p>
                                </div>
                            </li>
                        
                            <li class="list-group-item d-flex justify-content-between">
                                <label>DistanceKm</label>
                                <div>
                                    <p class="my-0">@details.DistanceKm</p>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between">
                                <label>AchievedDate</label>
                                <div>
                                    <p class="my-0">@details.AchievedDate</p>
                                </div>
                            </li>
                            }

                        </ul>
                    </div>
                    <div class="col-12 col-lg-5 offset-lg-1">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-info">Customer ScheduledSession:</span>
                        </h4>
                        <div @*class="col-4 text-right"*@>
                            <a asp-controller="ScheduledSession" asp-action="Create" asp-route-id="@Model.Customer.Id" class="btn btn-outline-info">Add a schedulesession</a>
                        </div>
                        <ul class="list-group mb-3">
                            @foreach (var details in Model.ScheduledSessionList.OrderByDescending(s => s.Date))
                            {
                                <li class="list-group-item d-flex justify-content-between">
                                    <label>Description</label>
                                    <div>
                                        <p class="my-0">@details.Description</p>
                                    </div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    <label>Date</label>
                                    <div>
                                        <p class="my-0">@details.Date</p>
                                    </div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between">
                                    <label>DurationMin</label>
                                    <div>
                                        <p class="my-0">@details.DurationMin</p>
                                    </div>
                                </li>
                            }

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

JuliePro/JuliePro/Views/Customer/CustomerTracking.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@model IEnumerable<JuliePro_Models.Models.Customer>
<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-8">
            <h2 class="text-info">The Customers</h2>
        </div>
        @*<div class=" col-2 text-right">
            <a asp-controller="Customer" asp-action="CustomerCard" class="btn btn-info form-control"> Add a trainer </a>
        </div>*@
    </div>
    <br />
    <div>

        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Trainer.FirstName)
                    </th>*@
                </tr>

                @*debut de la liste*@

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.Email
                        </td>
                        @*<td>
                            @item.Trainer.FirstName 
                        </td>*@
                        <td>
                            <a class="btn btn-primary text-white" asp-controller="Customer" asp-action="CustomerCard" asp-route-Id="@item.Id"> Edit </a>
                        </td>
                    </tr>
                }
                @*Fin de la liste*@
            </table>
        }
        @*else
        {
            <p>No Trainer exists.</p>
        }*@

    </div>
</div>