TP3_Depart/JuliePro/Controllers/CustomerController.cs
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models.ViewModels;
using JuliePro_Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JuliePro.Controllers
{
  public class CustomerController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;

    public CustomerController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }

    public IActionResult OurTrainers()
    {
      OurTrainersVM ourTrainersVM = new OurTrainersVM()
      {
        Trainers = _unitOfWork.Trainer.GetAllActive(),
        Specialities = _unitOfWork.Speciality.GetAll()
      };
      return View(ourTrainersVM);
    }


  }
}

TP3_Depart/JuliePro/Controllers/TrainerController.cs
using JuliePro_DataAccess.Repository.IRepository;
using JuliePro_Models;
using JuliePro_Models.ViewModels;
using JuliePro_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace JuliePro.Controllers
{
    [Authorize(Roles = AppConstants.SuperAdminRole + "," + AppConstants.TrainerRole)]
    public class TrainerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
    // permet d'avoir de chemin de la racine du site wwwroot
    private readonly IWebHostEnvironment _webHostEnvironment;

    public TrainerController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
    }


        [Authorize(Roles = AppConstants.SuperAdminRole + "," + AppConstants.TrainerRole)]
        public IActionResult Index()
        {
            IEnumerable<Trainer> listeTrainer = _unitOfWork.Trainer.GetAll(includeProperties:"Speciality");
            return View(listeTrainer);
        }

        //GET - UPSERT

        [Authorize(Roles = AppConstants.SuperAdminRole)]
        public IActionResult Upsert(int? id)
    {
      IEnumerable<Speciality> SpecialityList =  _unitOfWork.Speciality.GetAll();
      TrainerVM trainerVM = new TrainerVM()
      {
        Trainer = new Trainer()
      };

      if (id == null)
      {
        //CREATE
        return View(trainerVM);
      }
      else
      {
        //EDIT
        trainerVM.Trainer = _unitOfWork.Trainer.FirstOrDefault(filter: a => a.Id == id, includeProperties: "Speciality");

        if (trainerVM == null)
        {
          return NotFound();
        }
        return View(trainerVM);
      }

    }

        //POST - UPSERT
        [Authorize(Roles = AppConstants.SuperAdminRole)]
        [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(TrainerVM trainerVM)
    {
      if (ModelState.IsValid)
      {
        var files = HttpContext.Request.Form.Files;
        string webRootPath = _webHostEnvironment.WebRootPath;

        if (trainerVM.Trainer.Id == 0)
        {
          //Creating
          string upload = webRootPath + AppConstants.PhotoPathTrainers;
          string fileName = Guid.NewGuid().ToString();
          string extension = Path.GetExtension(files[0].FileName);

          using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
          {
            files[0].CopyTo(fileStream);
          }

          trainerVM.Trainer.Photo = fileName + extension;

          _unitOfWork.Trainer.Add(trainerVM.Trainer);
        }
        else
        {
          //updating
          var objFromDb = _unitOfWork.Trainer.FirstOrDefault(a => a.Id == trainerVM.Trainer.Id);
          if (files.Count > 0)
          {
            string upload = webRootPath + AppConstants.PhotoPathTrainers;
            string fileName = Guid.NewGuid().ToString();
            string extension = Path.GetExtension(files[0].FileName);

            if (trainerVM.Trainer.Photo != null)
            {
              var oldFile = Path.Combine(upload, objFromDb.Photo);

              if (System.IO.File.Exists(oldFile))
              {
                System.IO.File.Delete(oldFile);
              }
            }
            using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
            {
              files[0].CopyTo(fileStream);
            }

            trainerVM.Trainer.Photo = fileName + extension;
          }
          else
          {
            trainerVM.Trainer.Photo = objFromDb.Photo;
          }

          _unitOfWork.Trainer.Update(trainerVM.Trainer);

          _unitOfWork.Save();
          return RedirectToAction(nameof(Index));
        }
      }

      return View(trainerVM);
    }

        //GET DELETE

        [Authorize(Roles = AppConstants.SuperAdminRole)]
        public IActionResult Delete(int? id)
    {
      if (id == null || id == 0)
      {
        return NotFound();
      }

      var obj = _unitOfWork.Trainer.Get(id.GetValueOrDefault());
      if (obj == null)
      {
        return NotFound();
      }

      return View(obj);
    }

        //POST DELETE

        [Authorize(Roles = AppConstants.SuperAdminRole)]
        [HttpPost]
    [AutoValidateAntiforgeryToken]
    public IActionResult DeletePost(int? id)
    {
      var obj = _unitOfWork.Trainer.Get(id.GetValueOrDefault());
      if (obj == null)
      {
        return NotFound();
      }

       _unitOfWork.Trainer.Remove(obj);
      _unitOfWork.Save();

      return RedirectToAction("Index");
    }

    public IActionResult CustomerCard(int id)
    {
      CustomerVM customerVM = new CustomerVM()
      {
        Customer = _unitOfWork.Customer.FirstOrDefault(p => p.Id == id),
        SheduledSessionsList = _unitOfWork.ScheduledSession.GetAll(s => s.Customer_Id == id, includeProperties: "Training")

      };
      return View(customerVM);
    }

  }
}

TP3_Depart/JuliePro/Views/Shared/_CalendarEvents.cshtml
@model IEnumerable<CalendarEvent>

    <div class="col-8">
        <h2 class="text-info">Calendar Event</h2>
    </div> 

    <table class="table table-striped border">
        <tr class="table-secondary">
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </th>
        </tr>

        @*debut de la liste*@

        @foreach (var item in Model.OrderBy(c => c.Date).Take(3))
        {
            <tr>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    @item.Category.CategoryName
                </td>
            </tr>
        }
        @*Fin de la liste*@
    </table>

TP3_Depart/JuliePro/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" onclick="return validateInput()"  class="btn btn-primary form-control"><i class="far fa-plus-square"></i>Create</button>
    </div>
    <div class="col">
      <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-th-list"></i>&nbsp;Back to List</a>
    </div>
</div>

TP3_Depart/JuliePro/Views/Shared/_DeleteAndBackToListButton.cshtml
<div class="row">
    <div class="col">
      <button asp-action="DeletePost" class="btn btn-danger form-control" asp-route-id="@Model"><i class="far fa-trash-alt"></i>&nbsp;Delete</button>
    </div>
    <div class="col">
      <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-th-list"></i>&nbsp;Back to List</a>
    </div>
</div>

TP3_Depart/JuliePro/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
      <button type="submit" onclick="return validateInput()"  class="btn btn-warning form-control" asp-route-id="@Model"><i class="fas fa-pen"></i>&nbsp;Update</button>
    </div>
    <div class="col">
      <a asp-action="Index" class="btn btn-success form-control"><i class="fas fa-th-list"></i>&nbsp;Back to List</a>
    </div>
</div>

TP3_Depart/JuliePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - JuliePro</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link href="~/fontawesome/css/all.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/imagesLayout/tile.png" style="width:80%" /></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <partial name="_LoginPartial" />
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                @if (this.User.IsInRole(AppConstants.SuperAdminRole) || this.User.IsInRole(AppConstants.TrainerRole))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Trainer
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item">Tracking Training sessions</a></li>
                            <li><a class="dropdown-item">Tracking objectives</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Trainer" asp-action="Index">Profile</a></li>
                        </ul>
                    </li>

                }

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Customer
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item">Training sessions</a></li>
                        <li><a class="dropdown-item">Objective</a></li>
                        <li><a class="dropdown-item" asp-controller="Customer" asp-action="OurTrainers">Ours Trainers</a></li>
                    </ul>
                </li>

                @if (this.User.IsInRole(AppConstants.SuperAdminRole))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item">Training</a></li>
                            <li><a class="dropdown-item">Equipment</a></li>
                            <li><a class="dropdown-item">Speciality</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item">Manage Trainers</a></li>
                        </ul>
                    </li>
                }

            </ul>
        </div>
        <div class="col-md-2 text-right">
          @await Html.PartialAsync("_SelectLanguage")
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted bg-primary">
    <div class="container">
      &copy; 2021 - JuliePro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TP3_Depart/JuliePro/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}
<div style="display: inline-block; vertical-align: middle;">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        <div class="form-group" style="margin-bottom:0">
            <select onchange="this.form.submit()" name="culture" class="form-control btn btn-dark"
                    asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
            </select>
        </div>
    </form>
</div>